<?php

namespace AppBundle\Repository;

/**
 * EnginRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnginRepository extends \Doctrine\ORM\EntityRepository
{
}
