<?php

namespace AppBundle\Repository;

/**
 * ImageCarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageCarRepository extends \Doctrine\ORM\EntityRepository
{
}
