<?php

namespace AppBundle\Repository;

/**
 * ScooterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScooterRepository extends \Doctrine\ORM\EntityRepository
{
}
